[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .venv
    data
    orchestration/logs
    orchestration/dags/__pycache__
    src/__pycache__
    .ruff_cache
addopts = -q